create database toplevelpartyentities;

CREATE TABLE PARTY (
	PARTYID INT NOT NULL AUTO_INCREMENT,
	PARTYTYPEID INT NOT NULL,
	EXTERNALID INT NOT NULL,
	CURRENCYUOMID INT NOT NULL,
	DESCRIPTIONS VARCHAR(255),
	STATUSID INT NOT NULL,
	PRIMARY KEY (PARTYID)
);

CREATE TABLE PARTYGROUP (
	
	GROUPNAME VARCHAR(255),
	GROUPNAMELOCAL VARCHAR(255),
	OFFICESITENAME VARCHAR(255),
	COMMENTS VARCHAR(255),
	LOGOIMAGEURL VARCHAR(500),
    GROUP_PARTYID INT UNIQUE,
	 FOREIGN KEY (GROUP_PARTYID) REFERENCES PARTY(PARTYID)
);

CREATE TABLE PERSON (
	
	SALUTATION VARCHAR(255),
	FIRSTNAME VARCHAR(255),
	MIDDLENAME VARCHAR(255),
	LASTNAME VARCHAR(255),
	PERSONALTITLE VARCHAR(255),
	SUFFIX VARCHAR(255),
	GENDER VARCHAR(255),
	BIRTHDATE DATE,
	MARITALSTATUS VARCHAR(255),
    PERSON_PARTYID INT UNIQUE,
	FOREIGN KEY (PERSON_PARTYID) REFERENCES PARTY(PARTYID)
);


CREATE TABLE USERLOGIN (
	USERLOGINID varchar(225) NOT NULL,
	CURRENTPASSWORD VARCHAR(255),
	PASSWORDHINT VARCHAR(255),
	ISSYSTEMENABLED BOOLEAN,
	HASLOGGEDOUT BOOLEAN,
	REQUIREPASSWORDCHANGE BOOLEAN,
	LASTCURRENCYUOM INT,
	LASTLOCALE time,
	LASTTIMEZONE varchar(22),
	DISABLEDDATETIME datetime,
	SUCCESSIVEFAILEDLOGINS INT,
	USERLOGIN_PARTYID INT,
	PRIMARY KEY (USERLOGINID),
	FOREIGN KEY (USERLOGIN_PARTYID) REFERENCES PARTY(PARTYID)
);



CREATE TABLE CONTACTMECH (
	
	CONTACTMECHTYPEID INT NOT NULL,
	INFOSTRING VARCHAR(255),
	PCM_CONTACTMECHID INT,
    foreign key (PCM_CONTACTMECHID) references PARTYCONTACTMECH(CONTACTMECHID)
);

CREATE TABLE TOPLEVELPARTYENTITIES.PARTYCONTACTMECH (
		CONTACTMECHID INT NOT NULL auto_increment,
	FROMDATE DATE ,
	THRUDATE DATE,
	ROLETYPEID INT NOT NULL,
	ALLOWSOCIALIZATION BOOLEAN,
	EXTENSION BOOLEAN,
	VERIFIED BOOLEAN,
	YEARSWITHCONTACTMECH INT,
	MONTHSWITHCONTACTMECH INT,
    PCM_PARTYID INT,
   primary key (CONTACTMECHID),
	
	FOREIGN KEY (PCM_PARTYID) REFERENCES PARTY(PARTYID)
	
);

CREATE TABLE PARTYROLE (
PR_PARTYID INT,
ROLETYPEID INT,
FOREIGN KEY (PR_PARTYID) REFERENCES PARTY(PARTYID));

